### ISSUE TITLE
Should empty objects be generated

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#161] opened 2020-02-07 20:07 UTC
Hey Garrett, we're generating an empty object for [SourceDataStream](https://github.com/Azure/azure-rest-api-specs/blob/911f41bbbb59266f01ff8d1ac7fe230cf19a0204/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.0/FormRecognizer.json#L629) and before we weren't generating empty objects.

**Comment by lmazuel** [comment] 2020-02-07 21:27
Discussed that there is actually no problem. However the root cause can be addressed by:
https://github.com/Azure/autorest.modelerfour/issues/162

**Closed by lmazuel** 2020-02-07 21:27 UTC
Labels: Needs Discussion, P0 - Critical
