### ISSUE TITLE
Dictionary of Dictionaries has incorrect elementType schema 

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.modelerfour#106] opened 2020-01-04 00:41 UTC
This is from the body-dictionary.json on the test server:
![image](https://user-images.githubusercontent.com/17788297/71756975-88267980-2e47-11ea-803b-0d4ee12c3342.png)

What this should be is a DictionarySchema with elementType of DictionarySchema with elementType of string. Instead, you get a DictionarySchema with elementType of AnySchema:
![image](https://user-images.githubusercontent.com/17788297/71757018-b1470a00-2e47-11ea-9809-76f576e9fa0e.png)

So, the elementType should not be AnySchema. Even though the additionalProperties type is not a schema, I'd assume that anything which is type object with additionalProperties would be created as a DictionarySchema.

**Comment by fearthecowboy** [comment] 2020-02-14 21:48
Duplicate of #67 ?

**Closed by fearthecowboy** 2020-02-14 21:48 UTC
Labels: P1 - Required
